codecov:
  notify: {}
  require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range:
  - 90.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
ignore:
  - "**/AnalyzerResources.Designer.cs"
  - "**/CodeFixResources.Designer.cs"
  - "./Test/CSharpLatest.Test/ModuleInitializer.cs"
  - "./Test/CSharpLatest.Test/CSLUnitTests/TestTools.cs"
  - "./Test/CSharpLatest.Test/CSLUnitTests/Verifiers/*"
  - "./Test/CSharpLatest.Test/FieldBackedPropertyGenerator/Tools/TestHelper.cs"
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
