//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpLatest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnalyzerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalyzerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpLatest.AnalyzerResources", typeof(AnalyzerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables that are not modified should be made constants..
        /// </summary>
        internal static string CSL1000AnalyzerDescription {
            get {
                return ResourceManager.GetString("CSL1000AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; can be made constant.
        /// </summary>
        internal static string CSL1000AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CSL1000AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable can be made constant.
        /// </summary>
        internal static string CSL1000AnalyzerTitle {
            get {
                return ResourceManager.GetString("CSL1000AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;is null&apos; syntax instead of &apos;== null&apos;..
        /// </summary>
        internal static string CSL1001AnalyzerDescription {
            get {
                return ResourceManager.GetString("CSL1001AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can be changed to &apos;is null&apos;.
        /// </summary>
        internal static string CSL1001AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CSL1001AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression can be changed to &apos;is null&apos;.
        /// </summary>
        internal static string CSL1001AnalyzerTitle {
            get {
                return ResourceManager.GetString("CSL1001AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;is not null&apos; syntax instead of &apos;!= null&apos;..
        /// </summary>
        internal static string CSL1002AnalyzerDescription {
            get {
                return ResourceManager.GetString("CSL1002AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can be changed to &apos;is not null&apos;.
        /// </summary>
        internal static string CSL1002AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CSL1002AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression can be changed to &apos;is not null&apos;.
        /// </summary>
        internal static string CSL1002AnalyzerTitle {
            get {
                return ResourceManager.GetString("CSL1002AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using primary contructors to simplify your code..
        /// </summary>
        internal static string CSL1003AnalyzerDescription {
            get {
                return ResourceManager.GetString("CSL1003AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using a primary contructor for &apos;{0}&apos;.
        /// </summary>
        internal static string CSL1003AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CSL1003AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using primary contructors.
        /// </summary>
        internal static string CSL1003AnalyzerTitle {
            get {
                return ResourceManager.GetString("CSL1003AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using records to simplify your code. If a record is not appropriate, consider using a primary constructor..
        /// </summary>
        internal static string CSL1004AnalyzerDescription {
            get {
                return ResourceManager.GetString("CSL1004AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using a record for &apos;{0}&apos; (if a record is not appropriate, consider using a primary constructor).
        /// </summary>
        internal static string CSL1004AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CSL1004AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using records.
        /// </summary>
        internal static string CSL1004AnalyzerTitle {
            get {
                return ResourceManager.GetString("CSL1004AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify this one line getter to remove unnecessary clutter..
        /// </summary>
        internal static string CSL1005AnalyzerDescription {
            get {
                return ResourceManager.GetString("CSL1005AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify property {0} one line getter.
        /// </summary>
        internal static string CSL1005AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CSL1005AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify this one line getter.
        /// </summary>
        internal static string CSL1005AnalyzerTitle {
            get {
                return ResourceManager.GetString("CSL1005AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify this one line setter to remove unnecessary clutter..
        /// </summary>
        internal static string CSL1006AnalyzerDescription {
            get {
                return ResourceManager.GetString("CSL1006AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify property {0} one line setter.
        /// </summary>
        internal static string CSL1006AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CSL1006AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify this one line setter.
        /// </summary>
        internal static string CSL1006AnalyzerTitle {
            get {
                return ResourceManager.GetString("CSL1006AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing braces to a statement..
        /// </summary>
        internal static string CSL1007AnalyzerDescription {
            get {
                return ResourceManager.GetString("CSL1007AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing braces to &apos;{0}&apos; statement.
        /// </summary>
        internal static string CSL1007AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CSL1007AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing braces.
        /// </summary>
        internal static string CSL1007AnalyzerTitle {
            get {
                return ResourceManager.GetString("CSL1007AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unnecessary braces..
        /// </summary>
        internal static string CSL1008AnalyzerDescription {
            get {
                return ResourceManager.GetString("CSL1008AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unnecessary braces from &apos;{0}&apos; statement.
        /// </summary>
        internal static string CSL1008AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CSL1008AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unnecessary braces.
        /// </summary>
        internal static string CSL1008AnalyzerTitle {
            get {
                return ResourceManager.GetString("CSL1008AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyAttribute is missing argument..
        /// </summary>
        internal static string CSL1009AnalyzerDescription {
            get {
                return ResourceManager.GetString("CSL1009AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; is missing argument.
        /// </summary>
        internal static string CSL1009AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CSL1009AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute is missing argument.
        /// </summary>
        internal static string CSL1009AnalyzerTitle {
            get {
                return ResourceManager.GetString("CSL1009AnalyzerTitle", resourceCulture);
            }
        }
    }
}
