namespace CSharpLatest.AsyncEvent;

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

/// <summary>
/// Represents a dispatcher for asynchronous events with a specific sender type and event arguments type.
/// </summary>
/// <typeparam name="TSender">The type of the object raising the event.</typeparam>
/// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
public class AsyncEventDispatcher<TSender, TEventArgs>
    where TSender : class
    where TEventArgs : EventArgs
{
    private readonly ConcurrentDictionary<int, WeakReference<AsyncEventHandler<TSender, TEventArgs>>> _handlers = new();

    /// <summary>
    /// Registers an asynchronous event handler.
    /// </summary>
    /// <param name="handler">The event handler.</param>
    /// <exception cref="ArgumentNullException"><paramref name="handler"/> is <see langword="null"/>.</exception>
    public void Register(AsyncEventHandler<TSender, TEventArgs> handler)
    {
        if (handler is null)
            throw new ArgumentNullException(nameof(handler));

        WeakReference<AsyncEventHandler<TSender, TEventArgs>> weakReference = new(handler);
        int hashCode = handler.GetHashCode();
        _handlers[hashCode] = weakReference;
    }

    /// <summary>
    /// Unregisters an asynchronous event handler.
    /// </summary>
    /// <param name="handler">The event handler.</param>
    /// <exception cref="ArgumentNullException"><paramref name="handler"/> is <see langword="null"/>.</exception>
    public void Unregister(AsyncEventHandler<TSender, TEventArgs> handler)
    {
        if (handler is null)
            throw new ArgumentNullException(nameof(handler));

        int hashCode = handler.GetHashCode();
        _ = _handlers.TryRemove(hashCode, out _);
    }

    /// <summary>
    /// Inkokes all registered asynchronous event handlers.
    /// </summary>
    /// <param name="sender">The source of the event.</param>
    /// <param name="args">An object that contains the event data.</param>
    /// <param name="cancellationToken">The cancellation token that will be checked prior to completing the returned task.</param>
    public async Task InvokeAsync(TSender? sender, TEventArgs args, CancellationToken cancellationToken = default)
    {
        ICollection<WeakReference<AsyncEventHandler<TSender, TEventArgs>>> weakReferenceList = _handlers.Values;
        List<Task> tasks = [];
        bool isCleanupNeeded = false;

        foreach (WeakReference<AsyncEventHandler<TSender, TEventArgs>> weakReference in weakReferenceList)
            if (weakReference.TryGetTarget(out AsyncEventHandler<TSender, TEventArgs>? handler))
            {
                Task task = handler.Invoke(sender, args, cancellationToken);
                tasks.Add(task);
            }
            else
            {
                isCleanupNeeded = true;
            }

        if (isCleanupNeeded)
            Cleanup();

        await Task.WhenAll(tasks).ConfigureAwait(false);
    }

    private void Cleanup()
    {
        foreach (KeyValuePair<int, WeakReference<AsyncEventHandler<TSender, TEventArgs>>> entry in _handlers)
        {
            int key = entry.Key;
            WeakReference<AsyncEventHandler<TSender, TEventArgs>> weakReference = entry.Value;

            if (!weakReference.TryGetTarget(out _))
                _ = _handlers.TryRemove(key, out _);
        }
    }
}
